### ISSUE TITLE
org.gitlab4j.api.GitLabApiException: 404 Not found while calling acceptMergeRequests

### ISSUE THREAD

**Issue by rkskarthik** [gmessner/gitlab4j-api#121]
Here is my code : 

mergeCommitMessage="Merge using GitLab-4j-Api";
GitLabApi gitLabApi = new GitLabApi(Constants.GIT_URL, Constants.GIT_AUTHTOKEN);
MergeRequest autoMerge_result = gitLabApi.getMergeRequestApi().acceptMergeRequest(Constants.GIT_PROJECT_ID, REQ_ID,mergeCommitMessage, false, false);

SEVERE: Servlet.service() for servlet [Jersey Web Application] in context with path threw exception [org.glassfish.jersey.server.ContainerException: org.gitlab4j.api.GitLabApiException: 404 Not found] with root cause
org.gitlab4j.api.GitLabApiException: 404 Not found
	at org.gitlab4j.api.AbstractApi.validate(AbstractApi.java:304)
	at org.gitlab4j.api.AbstractApi.put(AbstractApi.java:174)
	at org.gitlab4j.api.MergeRequestApi.acceptMergeRequest(MergeRequestApi.java:351)
	at com.my.rest.GitLabProcessor.acceptMergeRequests(GitLabProcessor.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by rkskarthik** [comment]
And we need to pass optional params also
Exception:
The method acceptMergeRequest(Integer, Integer, String, Boolean, Boolean) in the type MergeRequestApi is not applicable for the arguments (Integer, Integer)

**Comment by gmessner** [comment]
@rkskarthik 
Are you passing in the ID or **_IID (internal ID)_** of the merge request?  You need to be passing in the **_IID (internal ID)_**, or it will result in a 404.  If you are already passing in the **_IID_**, let me know and I will troubleshoot the problem.

I have updated the Javadocs to be clearer that the **_IID (internal ID)_** is needed as well as added an acceptMergeRequest(Integer projectId, Integer mergeRequestIid) method as a convenience. These changes have been pushed, I will do a release tomorrow with the changes once unit tests have been created to test.

Concerning the optional parameters, just pass null in for mergeCommitMessage, shouldRemoveSourceBranch, and mergeWhenPipelineSucceeds

**Comment by gmessner** [comment]
@rkskarthik 
I have completed manual testing of the acceptMergeRequest() methods.  Everything works correctly as long as you use the merge request IID.

Release 4.7.10 is now available with the new acceptMergeRequest(Integer, Integer) method and clearer Javadocs concerning the use of merge request IID.
