### ISSUE TITLE
Does not work in Java 9

### ISSUE THREAD

**Issue by Foorack** [gmessner/gitlab4j-api#129]
I have to add `--add-modules=java.xml.bind` to the arg line for it to work. Might either want to fix or document that. :smiley:

**Comment by gmessner** [comment]
@Foorack 
I have added a dependency on javax.xml.bind 2.3.0 in release 4.7.16.  This should correct the issue for you, if it does, please close this issue, if it does not, please let me know.

**Comment by Foorack** [comment]
@gmessner That indeed fixed the missing classes with java.xml.bind, but it still complains about other missing classes, more specifically javax.activation.DataSource. I have to add `--add-modules=java.activation` for it to work.

```
        .... and the list goes on upwards, internal glassfish stuff, massive error ....
        at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:108)                                                       
        at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:99)                                                        
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:419)                                               
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:319)                                                  
        at org.gitlab4j.api.GitLabApiClient.getWithAccepts(GitLabApiClient.java:358)
        at org.gitlab4j.api.GitLabApiClient.getWithAccepts(GitLabApiClient.java:345)
        at org.gitlab4j.api.AbstractApi.getWithAccepts(AbstractApi.java:84)
        at org.gitlab4j.api.RepositoryApi.getRepositoryArchive(RepositoryApi.java:443)
        at net.********.********.********.<init>(********.java:24)
        at net.********.********.Main.main(Main.java:11)
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        ... 48 more
```

Similar error and interesting discussion: https://github.com/javaee/javamail/issues/266

Short them fix would just be to shade in add `java.activation`.
Possible long term fix?: https://stackoverflow.com/a/46493809/2479087

**Comment by Foorack** [comment]
Related? https://github.com/javaee/glassfish/issues/21588

**Comment by gmessner** [comment]
@Foorack 
After researching this, I've also added javax.activation as a dependency and release 4.7.17.  I don't have time right now to thoroughly test this on Java 9, so please let me know how it goes.

**Comment by Foorack** [comment]
@gmessner The error indicates this is something which originates in glassfish so I think it should be their responsibility to shade it in. I also don't know of the status of the java.activation module if/when it will be deprecated or not, i.e. how long this fix will work.

But yes, I can confirm 4.7.17 fixes running under Java 9. :white_check_mark:

**Comment by gmessner** [comment]
@Foorack 
I believe that including the javax.xml.bind and javax.activation might be causing issues elsewhere. 

I'm thinking about reverting those changes, adding notes to the docs about using with Java 9, and then properly fixing this for Java 9.  When I say properly, I need to actually build and use with Java 9, to date I have only done this with Java 8 and have not tested these changes on Java 9.

I also found an article that clearly explains the whys of this, basically, Java 9 moved 6 modules out of SE as they are part of EE:
http://www.logicbig.com/tutorials/core-java-tutorial/modules/root-modules/

**Comment by gmessner** [comment]
@Foorack 
After additional thought a\nd reaching out to a few users, I have decided to go ahead and leave the javax.xml.bind and javax.activation dependencies in place, so am closing this issue as fixed.
