### ISSUE TITLE
error when create the projects

### ISSUE THREAD

**Issue by aximo** [gmessner/gitlab4j-api#18]
I get one issue when creating project,any suggestion or help,thanks
```
<dependency>
	    <groupId>org.gitlab4j</groupId>
	    <artifactId>gitlab4j-api</artifactId>
	    <version>4.1.2</version>
	</dependency>
```

```
org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyWriter not found for media type=application/x-www-form-urlencoded, type=class org.gitlab4j.api.GitLabApiForm, genericType=class org.gitlab4j.api.GitLabApiForm.
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:247) ~[jersey-common-2.25.1.jar:na]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162) ~[jersey-common-2.25.1.jar:na]
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1130) ~[jersey-common-2.25.1.jar:na]
	at org.glassfish.jersey.client.ClientRequest.doWriteEntity(ClientRequest.java:517) ~[jersey-client-2.25.1.jar:na]
	at org.glassfish.jersey.client.ClientRequest.writeEntity(ClientRequest.java:499) ~[jersey-client-2.25.1.jar:na]
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:393) ~[jersey-client-2.25.1.jar:na]
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:285) ~[jersey-client-2.25.1.jar:na]
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252) ~[jersey-client-2.25.1.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684) ~[jersey-client-2.25.1.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681) ~[jersey-client-2.25.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.25.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.25.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228) ~[jersey-common-2.25.1.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444) ~[jersey-common-2.25.1.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681) ~[jersey-client-2.25.1.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:437) ~[jersey-client-2.25.1.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:343) ~[jersey-client-2.25.1.jar:na]
	at org.gitlab4j.api.GitLabApiClient.post(GitLabApiClient.java:283) ~[gitlab4j-api-4.1.2.jar:na]
	at org.gitlab4j.api.GitLabApiClient.post(GitLabApiClient.java:257) ~[gitlab4j-api-4.1.2.jar:na]
	at org.gitlab4j.api.AbstractApi.post(AbstractApi.java:73) ~[gitlab4j-api-4.1.2.jar:na]
	at org.gitlab4j.api.ProjectApi.createProject(ProjectApi.java:189) ~[gitlab4j-api-4.1.2.jar:na]
	at org.gitlab4j.api.ProjectApi.createProject(ProjectApi.java:140) ~[gitlab4j-api-4.1.2.jar:na]
```

**Comment by gmessner** [comment]
I have developed a fix for this and will get it checked in later today after I have created a unit test for it.

**Comment by gmessner** [comment]
This is fixed and tested.  4.1.4 has been pushed to the Maven repositories.  

Thank you for reporting the issue.

**Comment by gmessner** [comment]
Ijust followed this up with release 4.1.5, you should use that version.

**Comment by aximo** [comment]
validated, thanks
