### ISSUE TITLE
Error happens  - java.lang.NoSuchFieldError: SNAKE_CASE

### ISSUE THREAD

**Issue by vvaliavskyi** [gmessner/gitlab4j-api#184]
Hello, I met such error in my application -  java.lang.NoSuchFieldError: SNAKE_CASE.
The stack trace is provided below : 

WARNING: Unknown HK2 failure detected:
MultiException stack 1 of 2
java.lang.NoSuchFieldError: SNAKE_CASE
	at org.gitlab4j.api.utils.JacksonJson.<init>(JacksonJson.java:61)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.glassfish.hk2.utilities.reflection.ReflectionHelper.makeMe(ReflectionHelper.java:1375)
	at org.jvnet.hk2.internal.ClazzCreator.createMe(ClazzCreator.java:272)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:366)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:71)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154)
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199)
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:122)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetAllServiceHandles(ServiceLocatorImpl.java:1491)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServices(ServiceLocatorImpl.java:818)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getAllInstances(AbstractHk2InjectionManager.java:194)
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getAllInstances(ImmediateHk2InjectionManager.java:54)
	at org.glassfish.jersey.internal.ContextResolverFactory$ContextResolversConfigurator.postInit(ContextResolverFactory.java:93)
	at org.glassfish.jersey.client.ClientConfig$State.lambda$initRuntime$2(ClientConfig.java:470)
	at java.util.Arrays$ArrayList.forEach(Unknown Source)
	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:470)
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:341)
	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:826)
	at org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:285)
	at org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:143)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:112)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:108)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:99)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:445)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:351)
	at org.gitlab4j.api.GitLabApiClient.post(GitLabApiClient.java:433)
	at org.gitlab4j.api.GitLabApiClient.post(GitLabApiClient.java:404)
	at org.gitlab4j.api.AbstractApi.post(AbstractApi.java:159)
	at org.gitlab4j.api.SessionApi.login(SessionApi.java:39)
	at org.gitlab4j.api.GitLabApi.login(GitLabApi.java:398)
	at com.app.core.scm.gitclient.GitApiProvider.initApi(GitApiProvider.java:53)
	at com.app.core.scm.gitclient.GitApiProvider.<init>(GitApiProvider.java:49)
	at com.app.core.executor.loader.GitStorageLoader.load(GitStorageLoader.java:39)
	at com.app.core.impl.Core.loadData(Core.java:77)
	at com.app.ui.fx.adapter.CorePortFXDialogAdapter.loadData(CorePortFXDialogAdapter.java:61)
	at com.app.ui.fx.tasks.LoadStorageTask.call(LoadStorageTask.java:24)
	at com.app.ui.fx.tasks.LoadStorageTask.call(LoadStorageTask.java:1)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
MultiException stack 2 of 2
java.lang.IllegalStateException: Unable to perform operation: create on org.gitlab4j.api.utils.JacksonJson
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:393)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:71)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154)
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199)
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:122)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetAllServiceHandles(ServiceLocatorImpl.java:1491)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServices(ServiceLocatorImpl.java:818)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getAllInstances(AbstractHk2InjectionManager.java:194)
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getAllInstances(ImmediateHk2InjectionManager.java:54)
	at org.glassfish.jersey.internal.ContextResolverFactory$ContextResolversConfigurator.postInit(ContextResolverFactory.java:93)
	at org.glassfish.jersey.client.ClientConfig$State.lambda$initRuntime$2(ClientConfig.java:470)
	at java.util.Arrays$ArrayList.forEach(Unknown Source)
	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:470)
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:341)
	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:826)
	at org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:285)
	at org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:143)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:112)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:108)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:99)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:445)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:351)
	at org.gitlab4j.api.GitLabApiClient.post(GitLabApiClient.java:433)
	at org.gitlab4j.api.GitLabApiClient.post(GitLabApiClient.java:404)
	at org.gitlab4j.api.AbstractApi.post(AbstractApi.java:159)
	at org.gitlab4j.api.SessionApi.login(SessionApi.java:39)
	at org.gitlab4j.api.GitLabApi.login(GitLabApi.java:398)
	at com.app.core.scm.gitclient.GitApiProvider.initApi(GitApiProvider.java:53)
	at com.app.core.scm.gitclient.GitApiProvider.<init>(GitApiProvider.java:49)
	at com.app.core.executor.loader.GitStorageLoader.load(GitStorageLoader.java:39)
	at com.app.core.impl.Core.loadData(Core.java:77)
	at com.app.ui.fx.adapter.CorePortFXDialogAdapter.loadData(CorePortFXDialogAdapter.java:61)
	at com.app.ui.fx.tasks.LoadStorageTask.call(LoadStorageTask.java:24)
	at com.app.ui.fx.tasks.LoadStorageTask.call(LoadStorageTask.java:1)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by gmessner** [comment]
@vvaliavskyi 
This is usually due to the application specifying an old version of `com.fasterxml.jackson` being used.  This library is using Jackson 2.9.3, do you have and old version of a `com.fasterxml.jackson` dependency in you build?

**Comment by vvaliavskyi** [comment]
@gmessner 
Thanks for your reply. We use these dependencies:

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.9.3</version>
        </dependency>

        
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.9.3</version>
        </dependency>

**Comment by gmessner** [comment]
@vvaliavskyi 
It is likely that one of you other dependencies is pulling in an earlier version.  Do you have a way to look at your effective pom?

**Comment by vvaliavskyi** [comment]
@gmessner
I updated my dependencies up to 2.9.5. I checked effective pom - all jackson dependencies are corrrect (2.9.3 or 2.9.5). I looked at my local .m2 repo - all jars(from pom + transitive) are correct, except jackson-parent(it has 2.9.0).
I log in using the following method:
gitLabApi = GitLabApi.oauth2Login(ApiVersion.V4, serverUrl, credentials.getLogin(), credentials.getPassword(), null, null, false);

**Comment by gmessner** [comment]
@vvaliavskyi 
Have you resolved this issue?

**Comment by gmessner** [comment]
@vvaliavskyi 
I'm assuming that you resolved this, if not you can always reopen the issue.

**Comment by vvaliavskyi** [comment]
@gmessner 
Sorry, for late response. I clean cache from local maven repo again and problem went away. So status is not issue is completely correct.
Thanks
