### ISSUE TITLE
position[position_type] does not have a valid value

### ISSUE THREAD

**Issue by tomasbjerre** [gmessner/gitlab4j-api#308]
I'm getting:
```
org.gitlab4j.api.GitLabApiException: position[position_type] does not have a valid value
```

When using the text position type: `position.setPositionType(Position.PositionType.TEXT);`

I suspect this:
```
        private static JacksonJsonEnumHelper<PositionType> enumHelper = new JacksonJsonEnumHelper<>(PositionType.class,
                true, true);
```

Should be:
```
        private static JacksonJsonEnumHelper<PositionType> enumHelper = new JacksonJsonEnumHelper<>(PositionType.class,
                false, false);
```

Because the docs: https://docs.gitlab.com/ce/api/discussions.html has lower case `"position_type": "text",`.

Some more logging:
```
elected ExecutorServiceProvider implementation [org.glassfish.jersey.client.DefaultClientAsyncExecutorProvider] to be used for injection of executor qualified by [org.glassfish.jersey.client.ClientAsyncExecutor] annotation.
Selected ScheduledExecutorServiceProvider implementation [org.glassfish.jersey.client.DefaultClientBackgroundSchedulerProvider] to be used for injection of scheduler qualified by [org.glassfish.jersey.client.ClientBackgroundScheduler] annotation.
Restricted headers are not enabled using [sun.net.http.allowRestrictedHeaders] system property (setting only takes effect on connections created after the property has been set/changed).
1 * Sending client request on thread main
1 > POST https://gitlab.com/api/v4/projects/2732496/merge_requests/1/discussions
1 > Accept: application/json
1 > Content-Type: application/x-www-form-urlencoded
1 > PRIVATE-TOKEN: hhhvhvvhh
body=**Reporter**%3A+Checkstyle%0A%0A**Rule**%3A+com.puppycrawl.tools.checkstyle.checks.blocks.EmptyBlockCheck%0A%0A**Severity**%3A+INFO%0A%0A**File**%3A+%2Fhome%2Fbjerre%2Fworkspace%2Fviolations-test%2Fsrc%2Fmain%2Fjava%2Fse%2Fbjurr%2Fviolations%2Flib%2Fexample%2FOtherClass.java+L10%0A%0A%0AMust+have+at+least+one+statement.%0A%0A%0A*%3Cthis+is+a+auto+generated+comment+from+violation-comments-lib+F7F8ASD8123FSDF%3E*+*%3Ca673279742%3E*&position%5Bbase_sha%5D=e746f44de4cac5b4a4362e6713a3416e1e6617d3&position%5Bstart_sha%5D=a06971bdc77855da448a35da3313d20123320240&position%5Bhead_sha%5D=7e23c9a980197fe49fae67fb23687c857ff42f86&position%5Bposition_type%5D=Text&position%5Bnew_path%5D=src%2Fmain%2Fjava%2Fse%2Fbjurr%2Fviolations%2Flib%2Fexample%2FOtherClass.java&position%5Bnew_line%5D=10&position%5Bold_path%5D=src%2Fmain%2Fjava%2Fse%2Fbjurr%2Fviolations%2Flib%2Fexample%2FOtherClass.java&position%5Bold_line%5D=10

1 * Client response received on thread main
1 < 400
1 < Cache-Control: no-cache
1 < Content-Length: 63
1 < Content-Type: application/json
1 < Date: Tue, 19 Feb 2019 20:12:32 GMT
1 < RateLimit-Limit: 600
1 < RateLimit-Observed: 2
1 < RateLimit-Remaining: 598
1 < RateLimit-Reset: 1550607212
1 < RateLimit-ResetTime: Wed, 19 Feb 2019 20:13:32 GMT
1 < Server: nginx
1 < Vary: Origin
1 < X-Content-Type-Options: nosniff
1 < X-Frame-Options: SAMEORIGIN
1 < X-Request-Id: YmfAKIJ80e
1 < X-Runtime: 0.055948
{"error":"position[position_type] does not have a valid value"}

Could not create diff discussion!
ProjectID: 2732496
SourceSha: e746f44de4cac5b4a4362e6713a3416e1e6617d3
HeadSha: 7e23c9a980197fe49fae67fb23687c857ff42f86
TargetSha: a06971bdc77855da448a35da3313d20123320240
Path src/main/java/se/bjurr/violations/lib/example/OtherClass.java
Violation: **Reporter**: Checkstyle

**Rule**: com.puppycrawl.tools.checkstyle.checks.blocks.EmptyBlockCheck

**Severity**: INFO

**File**: /home/bjerre/workspace/violations-test/src/main/java/se/bjurr/violations/lib/example/OtherClass.java L10


Must have at least one statement.


*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a673279742>*
NewLine 10, OldLine10
org.gitlab4j.api.GitLabApiException: position[position_type] does not have a valid value
	at org.gitlab4j.api.AbstractApi.validate(AbstractApi.java:593)
	at org.gitlab4j.api.AbstractApi.post(AbstractApi.java:264)
	at org.gitlab4j.api.DiscussionsApi.createMergeRequestDiscussion(DiscussionsApi.java:332)
	at se.bjurr.violations.comments.gitlab.lib.GitLabCommentsProvider.createSingleFileComment(GitLabCommentsProvider.java:180)
```

**Comment by tomasbjerre** [comment]
I verified that this is the problem. Was able to create comment with this change. See PR #309
