### ISSUE TITLE
Cannot deserialize instance of java.util.ArrayList out of START_OBJECT token

### ISSUE THREAD

**Issue by jkomyno** [gmessner/gitlab4j-api#331]
Hi, I'm reading the issue events sent by GitLab's webhooks and I'm using gitlab4j-api v4.9.22.
Unfortunately, I'm facing the error `Cannot deserialize instance of java.util.ArrayList out of START_OBJECT token` when I use this library's WebhookManager to parse the response. It didn't happen with version v4.9.14 (the one I used earlier). Any tips?

**Comment by gmessner** [comment]
@jkomyno 
Would it be possible for you to capture the JSON and provide that here?

**Comment by gmessner** [comment]
@jkomyno 
Release 4.9.21 introduced a change that broke this.  It was implemented based on the documentation at:
https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#issues-events

Turns out, the documentation is wrong.  I have re-implemented the change using the actual content of the events being sent and released 4.9.23 with this fix.  I will be submitting a bug to GitLab concerning the documentation problem.

If you could verify the fix and close this issue it would be greatly appreciated.

**Comment by jkomyno** [comment]
Thank you, I can confirm that with version 4.9.23 this problem is fixed.

**Comment by hamishcunningham** [comment]
hi, I seem to have a similar problem on 4.11.11 triggered with this code:

      GitLabApi gitLabApi = new GitLabApi(
        GitLabApi.ApiVersion.OAUTH2_CLIENT, 
        "https://gitlab.com",
        "my access token"
      );
      List<Project> projects = gitLabApi.getProjectApi().getProjects();

I get:

  Exception in thread "main" org.gitlab4j.api.GitLabApiException: Cannot deserialize instance of 
  `java.util.ArrayList` out of START_OBJECT token
  at [Source: (org.glassfish.jersey.client.internal.HttpUrlConnector$2); line: 1, column: 1]
        at org.gitlab4j.api.Pager.<init>(Pager.java:93)
        at org.gitlab4j.api.ProjectApi.getProjects(ProjectApi.java:106)
        at org.gitlab4j.api.ProjectApi.getProjects(ProjectApi.java:78)
        at org.gitlab4j.api.ProjectApi$getProjects.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
        at marking.GitRepo.connect(App.groovy:154)
        at marking.GitRepo$connect$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)

Any ideas? Tnx!
