### ISSUE TITLE
can't use login service

### ISSUE THREAD

**Issue by s18634879388** [gmessner/gitlab4j-api#335]
my code:
`try {
            GitLabApi gitLabApi = GitLabApi.login("url","name","password");
        } catch (GitLabApiException e) {
            e.printStackTrace();
        }`

exception:
`org.gitlab4j.api.GitLabApiException: RESTEASY004655: Unable to invoke request
	at org.gitlab4j.api.AbstractApi.handle(AbstractApi.java:344)
	at org.gitlab4j.api.AbstractApi.post(AbstractApi.java:122)
	at org.gitlab4j.api.SessionApi.login(SessionApi.java:39)
	at org.gitlab4j.api.GitLabApi.login(GitLabApi.java:237)
	at org.gitlab4j.api.GitLabApi.login(GitLabApi.java:209)
	at com.sitech.cmap.devops.wsg.controller.version.CipGitPrivateKeyController.save(CipGitPrivateKeyController.java:165)
	at sun.reflect.GeneratedMethodAccessor205.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:289)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:454)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.post(ClientInvocationBuilder.java:193)
	at org.gitlab4j.api.GitLabApiClient.post(GitLabApiClient.java:401)
	at org.gitlab4j.api.GitLabApiClient.post(GitLabApiClient.java:372)
	at org.gitlab4j.api.AbstractApi.post(AbstractApi.java:120)
	... 57 more
Caused by: javax.ws.rs.ProcessingException: RESTEASY003215: could not find writer for content-type application/x-www-form-urlencoded type: javax.ws.rs.core.Form
	at org.jboss.resteasy.core.interception.jaxrs.ClientWriterInterceptorContext.throwWriterNotFoundException(ClientWriterInterceptorContext.java:40)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.getWriter(AbstractWriterInterceptorContext.java:146)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:121)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.writeRequestBody(ClientInvocation.java:388)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.writeRequestBodyToOutputStream(ApacheHttpClient4Engine.java:589)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.buildEntity(ApacheHttpClient4Engine.java:557)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.loadHttpMethod(ApacheHttpClient4Engine.java:456)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:283)
	... 62 more`

**Comment by gmessner** [comment]
@s18634879388 
You must be using a very old version of this library.  The ```GitLabApi.login()``` methods were deprecated long ago and subsequently removed because the GitLab server stopped supporting username/password login.  You need to use the ```GitLabApi.oauth2login()``` methods in the newer version of this library.

**Comment by s18634879388** [comment]
@gmessner 
sorry，the GitLabApi.oauth2login() methods also has this problem.

**Comment by gmessner** [comment]
@s18634879388 
It looks like the problem is because the RESTEASY JAX-RS client is being used, this library requires the use of the Jersery JAX-RS client.  Is it possible for you to remove ```org.jboss.resteasy:resteasy-jaxrs``` from your dependencies?

**Comment by s18634879388** [comment]
@gmessner 
I'm used it on a new project, a different error has occureed.

`org.gitlab4j.api.GitLabApiException: A MultiException has 2 exceptions.  They are:
1. java.lang.NoSuchFieldError: SNAKE_CASE
2. java.lang.IllegalStateException: Unable to perform operation: create on org.gitlab4j.api.utils.JacksonJson`

**Comment by gmessner** [comment]
@s18634879388 
These are all dependency related and likely because your project is using a very old version of the com.fasterxml.jackson libraries.  This library requires 2.9.6 of the com.fasterxml.jackson libraries.

**Comment by s18634879388** [comment]
> @s18634879388
> It looks like the problem is because the RESTEASY JAX-RS client is being used, this library requires the use of the Jersery JAX-RS client. Is it possible for you to remove `org.jboss.resteasy:resteasy-jaxrs` from your dependencies?

Sorry, my project need these dependencies. so... is there another solution?

**Comment by gmessner** [comment]
@s18634879388
Good news, I have actually found a solution for this.  It's a 1 line change that forces the use of the Jersey Client, currently it us using auto-discovery, which is why it is picking up Resteasy.  

This does not address your project using an old version of Jackson, you will need to use a more current version.

I will be putting out a realease later today.

**Comment by s18634879388** [comment]
Thanks very mach !!

**Comment by gmessner** [comment]
@s18634879388 
4.10.7 has been released which explicitly uses the Jersey Client, it should help with your original issue concerning Resteasy.

**Comment by s18634879388** [comment]
very good!!! I tested it, very nice!
