### ISSUE TITLE
login error with API V3

### ISSUE THREAD

**Issue by 44010083** [gmessner/gitlab4j-api#49]
this is my java code:
GitLabApi gitLabApi = GitLabApi.login(ApiVersion.V3,url,username,password);

the  error message is:
Exception in thread "main" org.gitlab4j.api.GitLabApiException: Internal Server Error
at org.gitlab4j.api.AbstractApi.validate(AbstractApi.java:282)
at org.gitlab4j.api.AbstractApi.get(AbstractApi.java:61)
at org.gitlab4j.api.ProjectApi.getProjects(ProjectApi.java:37)

**Comment by gmessner** [comment]
This has been fixed and GitLab4J-API 4.4.2 has been released.
